# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-05-13 10:35
from __future__ import unicode_literals

from django.db import migrations
from django.core.management import call_command

def load_scope_definitions(apps, schema_editor):
    call_command("loaddata", "scopedefinitions.json")

class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_scope_definitions),
    ]

